export const LOAD_USER_INITIAL = "LOAD_USER_INITIAL";
export const SHOW_DETAILS_INITIAL = "SHOW_DETAILS_INITIAL";
export const LOAD_USER = "LOAD_USER";
export const SHOW_DETAILS = "SHOW_DETAILS";




